require('ultimate-autopair').setup({
  mapopt={noremap=true},
  cmap=true,
  bs={
    enable=true,
    overjump=true,
    space=true,
    multichar=true,
    fallback=nil,
  },
  cr={
    enable=true,
    autoclose=false,
    multichar={
      enable=false,
      markdown={{'```','```',pair=true,noalpha=true,next=true}},
      lua={{'then','end'},{'do','end'}},
    },
    addsemi={'rust'},
    fallback=nil,
  },
  space={
    enable=true,
    fallback=nil,
  },
  fastwarp={
    enable=true,
    hopout=false,
    map='<A-e>',
    rmap='<A-E>',
    Wmap='<A-C-e>',
    cmap='<A-e>',
    rcmap='<A-E>',
    Wcmap='<A-C-e>',
    multiline=true,
    fallback=nil,
  },
  fastend={
    enable=true,
    map='<A-$>',
    cmap='<A-$>',
    smart=false,
    fallback=nil,
  },
  extensions={
    {'cmdtype',{'/','?','@'}},
    --'indentblock',
    'multichar',
    'string',
    {'treenode',{inside={'comment'}}},
    'escape',
    'rules',
    'filetype',
    {'alpha',{before={"'"}}},
    {'suround',{'"',"'"}},
    {'fly',{')','}',']',' ',match=nil}},
  },
  default_pairs={
    {'(',')'},
    {"'","'",rules={{'when',{'option','lisp'},{'instring'},{'not',{'filetype','tex'}}}}},
    rules={ --only runs if the extension rules is loaded
        {[[\']],[[\']],rules={{'and',{'not',{'or',{'next',"'"},{'previous','\\',2}}},{'instring'}}}},
        {[[\"]],[[\"]],rules={{'and',{'not',{'or',{'next','"'},{'previous','\\',2}}},{'instring'}}}},
    },
    ft={

    },
  },
})
